steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      echo "**********"
      echo $BRANCH_NAME
      echo "**********"

- id: 'check env'
  name: 'alpine'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      VALID_ENVS=("dev" "prod")
      if [[ ! " ${VALID_ENVS[@]} " =~ " ${BRANCH_NAME} " ]]; then
        echo "Invalid environment: $BRANCH_NAME"
        exit 1
      fi

- id: 'tf init'
  name: 'hashicorp/terraform:1.10.5'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      cd $BRANCH_NAME
      terraform init
  waitFor: ['check env']

- id: 'tf plan'
  name: 'hashicorp/terraform:1.10.5'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      cd $BRANCH_NAME
      terraform plan
  waitFor: ['tf init']

- id: 'tf apply'
  name: 'hashicorp/terraform:1.10.5'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      cd $BRANCH_NAME
      terraform apply -auto-approve
  waitFor: ['tf plan']