name: Terraform CI/CD

on:
  push:
    branches:
      - dev
      - prod
  workflow_dispatch:

env:
  GCP_WORKLOAD_ID_PROVIDER: "projects/721692020413/locations/global/workloadIdentityPools/github-actions/providers/github" 
  GCP_SERVICE_ACCOUNT_EMAIL: "terraform-service-account@terraform-gcp-jnunortiz.iam.gserviceaccount.com"

jobs:
  run-all:
    name: Run Terraform
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: 'true'
          workload_identity_provider: ${{ env.GCP_WORKLOAD_ID_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT_EMAIL }}

      - id: 'gcloud'
        name: 'gcloud'
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud services list

      - name: Capture Credentials and Set Environment Variable
        run: |
          echo "Credentials file path: ${{ steps.auth.outputs.credentials_file_path }}"
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ steps.auth.outputs.credentials_file_path }}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Set TFVARS file and Set Environment-Specific Secrets
        run: |
          if [ "$GITHUB_REF" == "refs/heads/dev" ]; then
            echo "Using dev.tfvars"
            echo "TFVARS_FILE=dev.tfvars" >> $GITHUB_ENV
          elif [ "$GITHUB_REF" == "refs/heads/prod" ]; then
            echo "Using prod.tfvars"
            echo "TFVARS_FILE=prod.tfvars" >> $GITHUB_ENV
          fi

      - name: Check Environment Variables
        run: |
          echo "Deployment Environment: $DEPLOY_ENV"
          echo "GCP_WORKLOAD_ID_PROVIDER: ${{ env.GCP_WORKLOAD_ID_PROVIDER }}"
          echo "GCP_SERVICE_ACCOUNT_EMAIL: ${{ env.GCP_SERVICE_ACCOUNT_EMAIL }}"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file=${{ env.TFVARS_FILE }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=${{ env.TFVARS_FILE }}
