name: Terraform CI/CD

on:
  push:
    branches:
      - dev
      - prod

env:
  GCP_WORKLOAD_ID_PROVIDER: "projects/721692020413/locations/global/workloadIdentityPools/github-actions/providers/github"
  GCP_SERVICE_ACCOUNT_EMAIL: "terraform-service-account@terraform-gcp-jnunortiz.iam.gserviceaccount.com"

jobs:
  authenticate:
    name: Authenticate to Google Cloud
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ env.GCP_WORKLOAD_ID_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT_EMAIL }}

  setup-terraform:
    name: Setup Terraform
    needs: authenticate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Cache Terraform Binary and Plugins
        uses: actions/cache@v3
        with:
          path: |
            ~/.terraform.d/plugin-cache
            /usr/local/bin/terraform
          key: terraform-${{ runner.os }}-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            terraform-${{ runner.os }}-

      - name: Display Branch Name
        run: |
          echo "**********"
          echo "Branch: $GITHUB_REF"
          echo "**********"

      - id: set_branch_name
        name: Set Branch Name
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          echo "Branch name: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Validate Environment
        run: |
          VALID_ENVS=("dev" "prod")
          if [[ ! " ${VALID_ENVS[@]} " =~ " ${BRANCH_NAME} " ]]; then
            echo "Invalid environment: $BRANCH_NAME"
            exit 1
          fi
          echo "Valid environment: $BRANCH_NAME, proceeding with Terraform steps."

  terraform-plan:
    name: Terraform Plan
    needs: setup-terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Terraform Binary and Plugins
        uses: actions/cache@v3
        with:
          path: |
            ~/.terraform.d/plugin-cache
            /usr/local/bin/terraform
          key: terraform-${{ runner.os }}-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            terraform-${{ runner.os }}-

      - name: Terraform Init
        run: |
          echo "Using branch name: $BRANCH_NAME"
          if [ -d "$BRANCH_NAME" ]; then
            cd $BRANCH_NAME
            terraform init
          else
            echo "Directory $BRANCH_NAME does not exist, skipping terraform init."
          fi

      - name: Terraform Plan
        run: |
          if [ -d "$BRANCH_NAME" ]; then
            cd $BRANCH_NAME
            terraform plan
          else
            echo "Directory $BRANCH_NAME does not exist, skipping terraform plan."
          fi

  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Terraform Binary and Plugins
        uses: actions/cache@v3
        with:
          path: |
            ~/.terraform.d/plugin-cache
            /usr/local/bin/terraform
          key: terraform-${{ runner.os }}-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            terraform-${{ runner.os }}-

      - name: Terraform Apply
        run: |
          if [ -d "$BRANCH_NAME" ]; then
            cd $BRANCH_NAME
            terraform apply -auto-approve
          else
            echo "Directory $BRANCH_NAME does not exist, skipping terraform apply."
          fi
